from enum import Enum


class DogRaze(str, Enum):
    chihuahua = "chihuahua"
    bulldog = "bulldog"
    dalmata = "dalmata"
    golden = "golden"
    pastor_aleman = "pastor alemán"
    pastor = "pastor"
    pug = "pug"
    rottweiler = "rottweiler"
    shih_tzu = "shih tzu"
    yorkshire = "yorkshire"
    pitbull = "pitbull"
    boxer = "boxer"
    labrador = "labrador"
    beagle = "beagle"
    husky = "husky"
    basset_hound = "basset hound"
    doberman = "doberman"
    dachshund = "dachshund"
    poodle = "poodle"
    chow_chow = "chow chow"
    corgi = "corgi"
    collie = "collie"
    terrier = "terrier"
    schnauzer = "schnauzer"
    bichon_frise = "bichon frise"
    pomeranian = "pomeranian"
    maltes = "maltes"
    shiba_inu = "shiba inu"
    akita = "akita"
    american_staffordshire_terrier = "american staffordshire terrier"
    american_bulldog = "american bulldog"
    american_pit_bull_terrier = "american pit bull terrier"
    american_water_spaniel = "american water spaniel"
    australian_cattle_dog = "australian cattle dog"
    australian_shepherd = "australian shepherd"
    australian_terrier = "australian terrier"
    basenji = "basenji"
    bedlington_terrier = "bedlington terrier"
    bernese_mountain_dog = "bernese mountain dog"
    black_and_tan_coonhound = "black and tan coonhound"
    black_russian_terrier = "black russian terrier"
    bloodhound = "bloodhound"
    border_collie = "border collie"
    border_terrier = "border terrier"
    borzoi = "borzoi"
    boston_terrier = "boston terrier"
    bouvier_des_flandres = "bouvier des flandres"
    other = "other"
    # ... add more dog raze here
