name: Pytest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test env vars for python
          env:
            GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
            TEST_GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.TEST_GOOGLE_APPLICATION_CREDENTIALS }}
          run: pytest
