name: Pytest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - uses: c-py/action-dotenv-to-setenv@v2
      - run: |
          pytest
